name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
          SHOW_PROJECTS: "True"
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_LANGUAGE : "True"
          SHOW_SHORT_INFO : "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          SHOW_PROFILE_VIEWS : "True"
          LOCALE: "en"
